/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poo.mediateca;

/**
 *
 * @author Jazmine
 */
public class DVD extends javax.swing.JFrame {

    /**
     * Creates new form DVD
     */
    public DVD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblAgregarDVD = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        iconDVD = new javax.swing.JLabel();
        lblTituloDVD = new javax.swing.JLabel();
        txtTituloDVD = new javax.swing.JTextField();
        lblDirectorDVD = new javax.swing.JLabel();
        txtDirectorDVD = new javax.swing.JTextField();
        txtDuracionDVD = new javax.swing.JTextField();
        lblDuracionDVD = new javax.swing.JLabel();
        lblGeneroDVD = new javax.swing.JLabel();
        txtGeneroDVD = new javax.swing.JTextField();
        btnGuardarDVD = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(74, 49, 77));

        lblAgregarDVD.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblAgregarDVD.setForeground(new java.awt.Color(255, 255, 255));
        lblAgregarDVD.setText("Agregar nuevo DVD");

        iconDVD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_dvd_logo_50px.png"))); // NOI18N

        lblTituloDVD.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblTituloDVD.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloDVD.setText("Título:");

        txtTituloDVD.setColumns(1);
        txtTituloDVD.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtTituloDVD.setBorder(null);
        txtTituloDVD.setMargin(new java.awt.Insets(4, 2, 2, 4));
        txtTituloDVD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloDVDActionPerformed(evt);
            }
        });

        lblDirectorDVD.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblDirectorDVD.setForeground(new java.awt.Color(255, 255, 255));
        lblDirectorDVD.setText("Director:");

        txtDirectorDVD.setColumns(1);
        txtDirectorDVD.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtDirectorDVD.setBorder(null);
        txtDirectorDVD.setMargin(new java.awt.Insets(4, 2, 2, 4));
        txtDirectorDVD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDirectorDVDActionPerformed(evt);
            }
        });

        txtDuracionDVD.setColumns(1);
        txtDuracionDVD.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtDuracionDVD.setBorder(null);
        txtDuracionDVD.setMargin(new java.awt.Insets(4, 2, 2, 4));
        txtDuracionDVD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDuracionDVDActionPerformed(evt);
            }
        });

        lblDuracionDVD.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblDuracionDVD.setForeground(new java.awt.Color(255, 255, 255));
        lblDuracionDVD.setText("Duración:");

        lblGeneroDVD.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblGeneroDVD.setForeground(new java.awt.Color(255, 255, 255));
        lblGeneroDVD.setText("Género:");

        txtGeneroDVD.setColumns(1);
        txtGeneroDVD.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtGeneroDVD.setBorder(null);
        txtGeneroDVD.setMargin(new java.awt.Insets(4, 2, 2, 4));
        txtGeneroDVD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGeneroDVDActionPerformed(evt);
            }
        });

        btnGuardarDVD.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnGuardarDVD.setText("Guardar");
        btnGuardarDVD.setBorder(null);
        btnGuardarDVD.setOpaque(false);
        btnGuardarDVD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarDVDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(iconDVD))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(lblTituloDVD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTituloDVD, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblGeneroDVD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtGeneroDVD, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblDirectorDVD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDirectorDVD, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblDuracionDVD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDuracionDVD, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblAgregarDVD)
                        .addGap(84, 84, 84))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnGuardarDVD, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(136, 136, 136))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(lblAgregarDVD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(iconDVD)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTituloDVD, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTituloDVD))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDirectorDVD, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDirectorDVD))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDuracionDVD)
                    .addComponent(txtDuracionDVD, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGeneroDVD, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGeneroDVD))
                .addGap(47, 47, 47)
                .addComponent(btnGuardarDVD, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTituloDVDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloDVDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloDVDActionPerformed

    private void txtDirectorDVDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDirectorDVDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDirectorDVDActionPerformed

    private void txtDuracionDVDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDuracionDVDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDuracionDVDActionPerformed

    private void txtGeneroDVDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGeneroDVDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGeneroDVDActionPerformed

    private void btnGuardarDVDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarDVDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarDVDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DVD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DVD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DVD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DVD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DVD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarDVD;
    private javax.swing.JLabel iconDVD;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAgregarDVD;
    private javax.swing.JLabel lblDirectorDVD;
    private javax.swing.JLabel lblDuracionDVD;
    private javax.swing.JLabel lblGeneroDVD;
    private javax.swing.JLabel lblTituloDVD;
    public static javax.swing.JTextField txtDirectorDVD;
    public static javax.swing.JTextField txtDuracionDVD;
    public static javax.swing.JTextField txtGeneroDVD;
    public static javax.swing.JTextField txtTituloDVD;
    // End of variables declaration//GEN-END:variables
}
