/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poo.mediateca;

/**
 *
 * @author Jazmine
 */
public class EditarTipoMaterial extends javax.swing.JFrame {

    /**
     * Creates new form EditarTipoMaterial
     */
    public EditarTipoMaterial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        iconMaterial = new javax.swing.JLabel();
        lblTituloTipoMaterial = new javax.swing.JLabel();
        cboTipoMaterial = new javax.swing.JComboBox<>();
        lblTituloTipoMaterial1 = new javax.swing.JLabel();
        cboSubtipoMaterial = new javax.swing.JComboBox<>();
        btnGuardarTipo = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        lblTituloTipoMaterial2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(74, 49, 77));

        iconMaterial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-medios-64.png"))); // NOI18N

        lblTituloTipoMaterial.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblTituloTipoMaterial.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloTipoMaterial.setText("Tipo de Material");

        cboTipoMaterial.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        cboTipoMaterial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Material Escrito", "Material Audiovisual" }));
        cboTipoMaterial.setSelectedIndex(-1);
        cboTipoMaterial.setBorder(null);
        cboTipoMaterial.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboTipoMaterialItemStateChanged(evt);
            }
        });
        cboTipoMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTipoMaterialActionPerformed(evt);
            }
        });

        lblTituloTipoMaterial1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblTituloTipoMaterial1.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloTipoMaterial1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloTipoMaterial1.setText("Subtipo de Material");

        cboSubtipoMaterial.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        cboSubtipoMaterial.setBorder(null);

        btnGuardarTipo.setBackground(new java.awt.Color(255, 255, 255));
        btnGuardarTipo.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnGuardarTipo.setText("Continuar");
        btnGuardarTipo.setBorder(null);
        btnGuardarTipo.setOpaque(false);
        btnGuardarTipo.setPreferredSize(new java.awt.Dimension(45, 17));
        btnGuardarTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarTipoActionPerformed(evt);
            }
        });

        btnRegresar.setBackground(new java.awt.Color(255, 255, 255));
        btnRegresar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.setBorder(null);
        btnRegresar.setOpaque(false);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        lblTituloTipoMaterial2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblTituloTipoMaterial2.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloTipoMaterial2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloTipoMaterial2.setText("Seleccione para editar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(iconMaterial)
                        .addGap(142, 142, 142))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTituloTipoMaterial)
                        .addGap(121, 121, 121))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cboSubtipoMaterial, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboTipoMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(90, 90, 90))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardarTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloTipoMaterial2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(109, 109, 109)
                    .addComponent(lblTituloTipoMaterial1, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                    .addGap(110, 110, 110)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lblTituloTipoMaterial2)
                .addGap(18, 18, 18)
                .addComponent(iconMaterial)
                .addGap(40, 40, 40)
                .addComponent(lblTituloTipoMaterial)
                .addGap(18, 18, 18)
                .addComponent(cboTipoMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(cboSubtipoMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(btnGuardarTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(250, 250, 250)
                    .addComponent(lblTituloTipoMaterial1)
                    .addContainerGap(280, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboTipoMaterialItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboTipoMaterialItemStateChanged
        // TODO add your handling code here:
        //**Llenamos el combobox de Subtipo de Material, dependiendo de la opción seleccionada en el primer combobox
        String opcion =(String)cboTipoMaterial.getSelectedItem();
        if(opcion.equals("Material Escrito"))
        {cboSubtipoMaterial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Libro", "Revista"}));

        }if(opcion.equals("Material Audiovisual"))
        {cboSubtipoMaterial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"CD","DVD"}));}
    }//GEN-LAST:event_cboTipoMaterialItemStateChanged

    private void cboTipoMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTipoMaterialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboTipoMaterialActionPerformed

    private void btnGuardarTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarTipoActionPerformed
        // TODO add your handling code here:
        /**Abrir el formulario correspondiente según la opción seleccionada en el combobox de Subtipo material **/
        String item = cboSubtipoMaterial.getSelectedItem().toString();
        if(item.equals("Libro"))
        {
            dispose();
            EditarLibro elib = new EditarLibro();
            elib.setVisible(true);
        }
        if(item.equals("Revista"))
        {
            dispose();
            EditarRevista erev = new EditarRevista();
            erev.setVisible(true);
        }
        if(item.equals("CD"))
        {
            dispose();
            EditarCD ecd = new EditarCD();
            ecd.setVisible(true);
        }
        if(item.equals("DVD"))
        {
            dispose();
            EditarDVD edvd = new EditarDVD();
            edvd.setVisible(true);
        }

    }//GEN-LAST:event_btnGuardarTipoActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        dispose();
        Inicio ini = new Inicio();
        ini.setVisible(true);
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarTipoMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarTipoMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarTipoMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarTipoMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarTipoMaterial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarTipo;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cboSubtipoMaterial;
    private javax.swing.JComboBox<String> cboTipoMaterial;
    private javax.swing.JLabel iconMaterial;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTituloTipoMaterial;
    private javax.swing.JLabel lblTituloTipoMaterial1;
    private javax.swing.JLabel lblTituloTipoMaterial2;
    // End of variables declaration//GEN-END:variables
}
