/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poo.mediateca;

import controller.MaterialController;
import entity.Material;
import javax.swing.JButton;

/**
 *
 * @author Jazmine
 */
public class Inicio extends javax.swing.JFrame {
    Tablas t = new Tablas();
    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        t.ver_tabla(tblMostrar);
        t.obtenerDatos();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSide = new javax.swing.JPanel();
        btnSalir = new javax.swing.JPanel();
        lblSalir = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JPanel();
        lblAgregar = new javax.swing.JLabel();
        btnModificar = new javax.swing.JPanel();
        lblModificar = new javax.swing.JLabel();
        btnListar = new javax.swing.JPanel();
        lblListar = new javax.swing.JLabel();
        btnBorrar = new javax.swing.JPanel();
        lblBorrar = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMostrar1 = new javax.swing.JTable();
        lblMediatecaTitulo = new javax.swing.JLabel();
        iconInicio = new javax.swing.JLabel();
        separador = new javax.swing.JSeparator();
        pnlCenter = new javax.swing.JPanel();
        txtBarraBuscar = new javax.swing.JTextField();
        iconBuscar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMostrar = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlSide.setBackground(new java.awt.Color(74, 49, 77));
        pnlSide.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSalir.setBackground(new java.awt.Color(135, 91, 140));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSalirMousePressed(evt);
            }
        });

        lblSalir.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblSalir.setForeground(new java.awt.Color(255, 255, 255));
        lblSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-exit-20.png"))); // NOI18N
        lblSalir.setText("Salir");

        javax.swing.GroupLayout btnSalirLayout = new javax.swing.GroupLayout(btnSalir);
        btnSalir.setLayout(btnSalirLayout);
        btnSalirLayout.setHorizontalGroup(
            btnSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSalirLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblSalir)
                .addContainerGap(120, Short.MAX_VALUE))
        );
        btnSalirLayout.setVerticalGroup(
            btnSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnSalirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlSide.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 190, 50));

        btnAgregar.setBackground(new java.awt.Color(100, 67, 104));
        btnAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAgregarMousePressed(evt);
            }
        });

        lblAgregar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblAgregar.setForeground(new java.awt.Color(255, 255, 255));
        lblAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-add-new-20.png"))); // NOI18N
        lblAgregar.setText("Agregar Material");
        lblAgregar.setIconTextGap(6);

        javax.swing.GroupLayout btnAgregarLayout = new javax.swing.GroupLayout(btnAgregar);
        btnAgregar.setLayout(btnAgregarLayout);
        btnAgregarLayout.setHorizontalGroup(
            btnAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnAgregarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblAgregar)
                .addGap(32, 32, 32))
        );
        btnAgregarLayout.setVerticalGroup(
            btnAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnAgregarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlSide.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 190, 50));

        btnModificar.setBackground(new java.awt.Color(115, 77, 120));
        btnModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnModificarMousePressed(evt);
            }
        });

        lblModificar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblModificar.setForeground(new java.awt.Color(255, 255, 255));
        lblModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-edit-20.png"))); // NOI18N
        lblModificar.setText("Modificar Material");

        javax.swing.GroupLayout btnModificarLayout = new javax.swing.GroupLayout(btnModificar);
        btnModificar.setLayout(btnModificarLayout);
        btnModificarLayout.setHorizontalGroup(
            btnModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnModificarLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblModificar)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        btnModificarLayout.setVerticalGroup(
            btnModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnModificarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlSide.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 190, 50));

        btnListar.setBackground(new java.awt.Color(121, 81, 126));
        btnListar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblListar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblListar.setForeground(new java.awt.Color(255, 255, 255));
        lblListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-list-20.png"))); // NOI18N
        lblListar.setText("Listar Materiales");

        javax.swing.GroupLayout btnListarLayout = new javax.swing.GroupLayout(btnListar);
        btnListar.setLayout(btnListarLayout);
        btnListarLayout.setHorizontalGroup(
            btnListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnListarLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblListar)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        btnListarLayout.setVerticalGroup(
            btnListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnListarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblListar, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlSide.add(btnListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 190, 50));

        btnBorrar.setBackground(new java.awt.Color(128, 86, 133));
        btnBorrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBorrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBorrarMousePressed(evt);
            }
        });

        lblBorrar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblBorrar.setForeground(new java.awt.Color(255, 255, 255));
        lblBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-remove-20.png"))); // NOI18N
        lblBorrar.setText("Borrar Material");

        javax.swing.GroupLayout btnBorrarLayout = new javax.swing.GroupLayout(btnBorrar);
        btnBorrar.setLayout(btnBorrarLayout);
        btnBorrarLayout.setHorizontalGroup(
            btnBorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBorrarLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblBorrar)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        btnBorrarLayout.setVerticalGroup(
            btnBorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnBorrarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlSide.add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 190, 50));

        tblMostrar1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        jScrollPane2.setViewportView(tblMostrar1);

        pnlSide.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 810, 430));

        lblMediatecaTitulo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblMediatecaTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblMediatecaTitulo.setText("Mediateca");
        pnlSide.add(lblMediatecaTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        iconInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-media-80.png"))); // NOI18N
        pnlSide.add(iconInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 80, 93));
        pnlSide.add(separador, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 100, 10));

        getContentPane().add(pnlSide, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 530));

        pnlCenter.setBackground(new java.awt.Color(74, 49, 77));
        pnlCenter.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBarraBuscar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtBarraBuscar.setToolTipText("");
        txtBarraBuscar.setBorder(null);
        txtBarraBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBarraBuscarActionPerformed(evt);
            }
        });
        pnlCenter.add(txtBarraBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 90, 200, 20));

        iconBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-google-web-search-24.png"))); // NOI18N
        pnlCenter.add(iconBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 90, -1, 20));

        getContentPane().add(pnlCenter, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, -30, 830, 120));

        tblMostrar.setFont(new java.awt.Font("Century Gothic", 0, 12));
        tblMostrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMostrarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMostrar);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 810, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBarraBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBarraBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBarraBuscarActionPerformed

    private void btnSalirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirMousePressed

    private void btnAgregarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMousePressed
        // TODO add your handling code here:
        dispose();
        TipoMaterial tpm = new TipoMaterial();
        tpm.setVisible(true);
    }//GEN-LAST:event_btnAgregarMousePressed

    private void btnModificarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarMousePressed
        // TODO add your handling code here:
        dispose();
        EditarTipoMaterial tpe = new EditarTipoMaterial();
        tpe.setVisible(true);
    }//GEN-LAST:event_btnModificarMousePressed

    private void btnBorrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBorrarMousePressed
        // TODO add your handling code here:
        dispose();
        EliminarMaterial elm = new EliminarMaterial();
        elm.setVisible(true);
    }//GEN-LAST:event_btnBorrarMousePressed

    private void tblMostrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMostrarMouseClicked
        // TODO add your handling code here:
        // TODO add your handling code here:
        int column = tblMostrar.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY()/tblMostrar.getRowHeight();
        
        if(row<tblMostrar.getRowCount()&&row>=0&&column<tblMostrar.getColumnCount()&&column>=0){
            Object value = tblMostrar.getValueAt(row, column);
            if(value instanceof JButton){
                ((JButton)value).doClick();
                JButton boton = (JButton)value;
                
                if(boton.getName().equals("m")){
                    System.out.println("Diste click en modificar");
                    
                }
                if(boton.getName().equals("e")){
                    System.out.println("Diste click en eliminar");
                }
                
            }
        }
    }//GEN-LAST:event_tblMostrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnAgregar;
    private javax.swing.JPanel btnBorrar;
    private javax.swing.JPanel btnListar;
    private javax.swing.JPanel btnModificar;
    private javax.swing.JPanel btnSalir;
    private javax.swing.JLabel iconBuscar;
    private javax.swing.JLabel iconInicio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAgregar;
    private javax.swing.JLabel lblBorrar;
    private javax.swing.JLabel lblListar;
    private javax.swing.JLabel lblMediatecaTitulo;
    private javax.swing.JLabel lblModificar;
    private javax.swing.JLabel lblSalir;
    private javax.swing.JPanel pnlCenter;
    private javax.swing.JPanel pnlSide;
    private javax.swing.JSeparator separador;
    public static javax.swing.JTable tblMostrar;
    private javax.swing.JTable tblMostrar1;
    private javax.swing.JTextField txtBarraBuscar;
    // End of variables declaration//GEN-END:variables
}
