/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poo.mediateca;

import javax.swing.JOptionPane;

/**
 *
 * @author Jazmine
 */
public class Libro extends javax.swing.JFrame {

    /**
     * Creates new form Libro
     */
    public Libro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblLibro = new javax.swing.JLabel();
        iconLibro = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblAutorLibro = new javax.swing.JLabel();
        txtAutorLibro = new javax.swing.JTextField();
        lblNumPagsLibro = new javax.swing.JLabel();
        txtNumPagsLibro = new javax.swing.JTextField();
        lblEditorial = new javax.swing.JLabel();
        txtEditorial = new javax.swing.JTextField();
        lblISBN = new javax.swing.JLabel();
        txtISBN = new javax.swing.JTextField();
        lblPubYear = new javax.swing.JLabel();
        txtPubYear = new javax.swing.JTextField();
        btnGuardarLibro = new javax.swing.JButton();
        lblTituloLibro = new javax.swing.JLabel();
        txtTituloLibro = new javax.swing.JTextField();
        lblUnidadesLibros = new javax.swing.JLabel();
        txtUnidadesLibros = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        jPanel1.setBackground(new java.awt.Color(74, 49, 77));

        lblLibro.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblLibro.setForeground(new java.awt.Color(255, 255, 255));
        lblLibro.setText("Agregar nuevo Libro");

        iconLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_book_50px_1.png"))); // NOI18N

        lblAutorLibro.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblAutorLibro.setForeground(new java.awt.Color(255, 255, 255));
        lblAutorLibro.setText("Autor:");

        txtAutorLibro.setColumns(2);
        txtAutorLibro.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtAutorLibro.setBorder(null);
        txtAutorLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAutorLibroActionPerformed(evt);
            }
        });
        txtAutorLibro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAutorLibroKeyTyped(evt);
            }
        });

        lblNumPagsLibro.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblNumPagsLibro.setForeground(new java.awt.Color(255, 255, 255));
        lblNumPagsLibro.setText("Número de páginas:");

        txtNumPagsLibro.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtNumPagsLibro.setBorder(null);
        txtNumPagsLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumPagsLibroActionPerformed(evt);
            }
        });
        txtNumPagsLibro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumPagsLibroKeyTyped(evt);
            }
        });

        lblEditorial.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblEditorial.setForeground(new java.awt.Color(255, 255, 255));
        lblEditorial.setText("Editorial:");

        txtEditorial.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtEditorial.setBorder(null);
        txtEditorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEditorialActionPerformed(evt);
            }
        });

        lblISBN.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblISBN.setForeground(new java.awt.Color(255, 255, 255));
        lblISBN.setText("ISBN:");

        txtISBN.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtISBN.setBorder(null);
        txtISBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtISBNActionPerformed(evt);
            }
        });
        txtISBN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtISBNKeyTyped(evt);
            }
        });

        lblPubYear.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblPubYear.setForeground(new java.awt.Color(255, 255, 255));
        lblPubYear.setText("Año de publicación:");

        txtPubYear.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtPubYear.setBorder(null);
        txtPubYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPubYearActionPerformed(evt);
            }
        });
        txtPubYear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPubYearKeyTyped(evt);
            }
        });

        btnGuardarLibro.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnGuardarLibro.setText("Guardar");
        btnGuardarLibro.setBorder(null);
        btnGuardarLibro.setOpaque(false);

        lblTituloLibro.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblTituloLibro.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloLibro.setText("Título:");

        txtTituloLibro.setColumns(2);
        txtTituloLibro.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtTituloLibro.setBorder(null);
        txtTituloLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloLibroActionPerformed(evt);
            }
        });
        txtTituloLibro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTituloLibroKeyTyped(evt);
            }
        });

        lblUnidadesLibros.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblUnidadesLibros.setForeground(new java.awt.Color(255, 255, 255));
        lblUnidadesLibros.setText("Unidades disponibles:");

        txtUnidadesLibros.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtUnidadesLibros.setBorder(null);
        txtUnidadesLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUnidadesLibrosActionPerformed(evt);
            }
        });
        txtUnidadesLibros.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUnidadesLibrosKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(83, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(75, 75, 75))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(161, Short.MAX_VALUE)
                .addComponent(iconLibro)
                .addGap(148, 148, 148))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lblNumPagsLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(4, 4, 4)
                            .addComponent(txtNumPagsLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblPubYear, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPubYear))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnGuardarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblUnidadesLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtUnidadesLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(lblTituloLibro)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtTituloLibro))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(lblAutorLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(4, 4, 4)
                            .addComponent(txtAutorLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(62, 62, 62))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(iconLibro)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTituloLibro)
                    .addComponent(txtTituloLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAutorLibro)
                    .addComponent(txtAutorLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNumPagsLibro)
                    .addComponent(txtNumPagsLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEditorial)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblISBN))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPubYear, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPubYear))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUnidadesLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUnidadesLibros))))
                .addGap(43, 43, 43)
                .addComponent(btnGuardarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAutorLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAutorLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAutorLibroActionPerformed

    private void txtNumPagsLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumPagsLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumPagsLibroActionPerformed

    private void txtEditorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEditorialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEditorialActionPerformed

    private void txtISBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtISBNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtISBNActionPerformed

    private void txtPubYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPubYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPubYearActionPerformed

    private void txtTituloLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloLibroActionPerformed

    private void txtUnidadesLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnidadesLibrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUnidadesLibrosActionPerformed

    private void txtTituloLibroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTituloLibroKeyTyped
            // TODO add your handling code here:
                                     
    }//GEN-LAST:event_txtTituloLibroKeyTyped

    private void txtAutorLibroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAutorLibroKeyTyped
        // TODO add your handling code here:
   
    }//GEN-LAST:event_txtAutorLibroKeyTyped

    private void txtNumPagsLibroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumPagsLibroKeyTyped
        // TODO add your handling code here:
        //Validación para admitir solamente números
        char c = evt.getKeyChar();
            if(Character.isAlphabetic(c)){
                evt.consume();
                                     }
    }//GEN-LAST:event_txtNumPagsLibroKeyTyped

    private void txtPubYearKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPubYearKeyTyped
        // TODO add your handling code here:
         //Validación para admitir solamente números
        char c = evt.getKeyChar();
            if(Character.isAlphabetic(c)){
                evt.consume();
                }
    }//GEN-LAST:event_txtPubYearKeyTyped

    private void txtUnidadesLibrosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUnidadesLibrosKeyTyped
        // TODO add your handling code here:
         //Validación para admitir solamente números
        char c = evt.getKeyChar();
            if(Character.isAlphabetic(c)){
                evt.consume();
                }
    }//GEN-LAST:event_txtUnidadesLibrosKeyTyped

    private void txtISBNKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtISBNKeyTyped
        // TODO add your handling code here:
         //Validación para admitir solamente números
        char c = evt.getKeyChar();
            if(Character.isAlphabetic(c)){
                evt.consume();
                }
    }//GEN-LAST:event_txtISBNKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Libro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Libro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Libro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Libro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Libro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarLibro;
    private javax.swing.JLabel iconLibro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAutorLibro;
    private javax.swing.JLabel lblEditorial;
    private javax.swing.JLabel lblISBN;
    private javax.swing.JLabel lblLibro;
    private javax.swing.JLabel lblNumPagsLibro;
    private javax.swing.JLabel lblPubYear;
    private javax.swing.JLabel lblTituloLibro;
    private javax.swing.JLabel lblUnidadesLibros;
    public static javax.swing.JTextField txtAutorLibro;
    public static javax.swing.JTextField txtEditorial;
    public static javax.swing.JTextField txtISBN;
    public static javax.swing.JTextField txtNumPagsLibro;
    public static javax.swing.JTextField txtPubYear;
    public static javax.swing.JTextField txtTituloLibro;
    public static javax.swing.JTextField txtUnidadesLibros;
    // End of variables declaration//GEN-END:variables
}
