/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poo.mediateca;

/**
 *
 * @author Jazmine
 */
public class Revista extends javax.swing.JFrame {

    /**
     * Creates new form Revista
     */
    public Revista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblAgregarRevista = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        iconRevista = new javax.swing.JLabel();
        lblTituloRevista = new javax.swing.JLabel();
        txtTituloRevista = new javax.swing.JTextField();
        lblEditorialRevista = new javax.swing.JLabel();
        lblPeriodoRevista = new javax.swing.JLabel();
        txtPeriodoRevista = new javax.swing.JTextField();
        txtEditorialRevista = new javax.swing.JTextField();
        lblFechaPublicacion = new javax.swing.JLabel();
        txtFechaPublicacion = new javax.swing.JTextField();
        lblUnidadesRevista = new javax.swing.JLabel();
        txtUnidadesRevista = new javax.swing.JTextField();
        btnGuardarRevista = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setPreferredSize(new java.awt.Dimension(361, 531));

        jPanel1.setBackground(new java.awt.Color(74, 49, 77));

        lblAgregarRevista.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblAgregarRevista.setForeground(new java.awt.Color(255, 255, 255));
        lblAgregarRevista.setText("Agregar nueva Revista");

        iconRevista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_magazine_50px_1.png"))); // NOI18N

        lblTituloRevista.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblTituloRevista.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloRevista.setText("Título:");

        txtTituloRevista.setColumns(2);
        txtTituloRevista.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtTituloRevista.setBorder(null);
        txtTituloRevista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloRevistaActionPerformed(evt);
            }
        });

        lblEditorialRevista.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblEditorialRevista.setForeground(new java.awt.Color(255, 255, 255));
        lblEditorialRevista.setText("Editorial:");

        lblPeriodoRevista.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblPeriodoRevista.setForeground(new java.awt.Color(255, 255, 255));
        lblPeriodoRevista.setText("Periodicidad:");

        txtPeriodoRevista.setColumns(2);
        txtPeriodoRevista.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtPeriodoRevista.setBorder(null);
        txtPeriodoRevista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPeriodoRevistaActionPerformed(evt);
            }
        });

        txtEditorialRevista.setColumns(2);
        txtEditorialRevista.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtEditorialRevista.setBorder(null);
        txtEditorialRevista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEditorialRevistaActionPerformed(evt);
            }
        });

        lblFechaPublicacion.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblFechaPublicacion.setForeground(new java.awt.Color(255, 255, 255));
        lblFechaPublicacion.setText("Fecha de publicación:");

        txtFechaPublicacion.setColumns(2);
        txtFechaPublicacion.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtFechaPublicacion.setBorder(null);
        txtFechaPublicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaPublicacionActionPerformed(evt);
            }
        });
        txtFechaPublicacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFechaPublicacionKeyTyped(evt);
            }
        });

        lblUnidadesRevista.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblUnidadesRevista.setForeground(new java.awt.Color(255, 255, 255));
        lblUnidadesRevista.setText("Unidades disponibles:");

        txtUnidadesRevista.setColumns(2);
        txtUnidadesRevista.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtUnidadesRevista.setBorder(null);
        txtUnidadesRevista.setSelectionColor(new java.awt.Color(153, 153, 153));
        txtUnidadesRevista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUnidadesRevistaActionPerformed(evt);
            }
        });
        txtUnidadesRevista.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUnidadesRevistaKeyTyped(evt);
            }
        });

        btnGuardarRevista.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnGuardarRevista.setText("Guardar");
        btnGuardarRevista.setBorder(null);
        btnGuardarRevista.setOpaque(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lblTituloRevista)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtTituloRevista, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(lblPeriodoRevista)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtPeriodoRevista))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(lblEditorialRevista)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtEditorialRevista, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblFechaPublicacion)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnGuardarRevista, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblUnidadesRevista)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtUnidadesRevista, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtFechaPublicacion))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(82, 82, 82)
                            .addComponent(lblAgregarRevista))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(70, 70, 70)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(160, 160, 160)
                            .addComponent(iconRevista))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(lblAgregarRevista)
                .addGap(11, 11, 11)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(iconRevista)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTituloRevista, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTituloRevista))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEditorialRevista, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                    .addComponent(txtEditorialRevista, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPeriodoRevista)
                    .addComponent(txtPeriodoRevista, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFechaPublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFechaPublicacion))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUnidadesRevista, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUnidadesRevista))
                .addGap(45, 45, 45)
                .addComponent(btnGuardarRevista, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTituloRevistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloRevistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloRevistaActionPerformed

    private void txtPeriodoRevistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPeriodoRevistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPeriodoRevistaActionPerformed

    private void txtEditorialRevistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEditorialRevistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEditorialRevistaActionPerformed

    private void txtFechaPublicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaPublicacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaPublicacionActionPerformed

    private void txtUnidadesRevistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnidadesRevistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUnidadesRevistaActionPerformed

    private void txtFechaPublicacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFechaPublicacionKeyTyped
        // TODO add your handling code here:
         //Validación para admitir solamente números
        char c = evt.getKeyChar();
            if(Character.isAlphabetic(c)){
                evt.consume();
                }
    }//GEN-LAST:event_txtFechaPublicacionKeyTyped

    private void txtUnidadesRevistaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUnidadesRevistaKeyTyped
        // TODO add your handling code here:
         //Validación para admitir solamente números
        char c = evt.getKeyChar();
            if(Character.isAlphabetic(c)){
                evt.consume();
                }
    }//GEN-LAST:event_txtUnidadesRevistaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Revista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Revista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Revista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Revista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Revista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarRevista;
    private javax.swing.JLabel iconRevista;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAgregarRevista;
    private javax.swing.JLabel lblEditorialRevista;
    private javax.swing.JLabel lblFechaPublicacion;
    private javax.swing.JLabel lblPeriodoRevista;
    private javax.swing.JLabel lblTituloRevista;
    private javax.swing.JLabel lblUnidadesRevista;
    public static javax.swing.JTextField txtEditorialRevista;
    public static javax.swing.JTextField txtFechaPublicacion;
    public static javax.swing.JTextField txtPeriodoRevista;
    public static javax.swing.JTextField txtTituloRevista;
    public static javax.swing.JTextField txtUnidadesRevista;
    // End of variables declaration//GEN-END:variables
}
