/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poo.mediateca;

/**
 *
 * @author Jazmine
 */
public class TipoMaterial extends javax.swing.JFrame {

    /**
     * Creates new form TipoMaterial
     */
    public TipoMaterial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBackground = new javax.swing.JPanel();
        lblTituloTipoMaterial = new javax.swing.JLabel();
        iconMaterial = new javax.swing.JLabel();
        cboTipoMaterial = new javax.swing.JComboBox<>();
        cboSubtipoMaterial = new javax.swing.JComboBox<>();
        lblTituloTipoMaterial1 = new javax.swing.JLabel();
        btnGuardarTipo = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        pnlBackground.setBackground(new java.awt.Color(74, 49, 77));

        lblTituloTipoMaterial.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblTituloTipoMaterial.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloTipoMaterial.setText("Tipo de Material");

        iconMaterial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-medios-64.png"))); // NOI18N

        cboTipoMaterial.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        cboTipoMaterial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Material Escrito", "Material Audiovisual" }));
        cboTipoMaterial.setSelectedIndex(-1);
        cboTipoMaterial.setBorder(null);
        cboTipoMaterial.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboTipoMaterialItemStateChanged(evt);
            }
        });
        cboTipoMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTipoMaterialActionPerformed(evt);
            }
        });

        cboSubtipoMaterial.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        cboSubtipoMaterial.setBorder(null);
        cboSubtipoMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboSubtipoMaterialActionPerformed(evt);
            }
        });

        lblTituloTipoMaterial1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblTituloTipoMaterial1.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloTipoMaterial1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloTipoMaterial1.setText("Subtipo de Material");

        btnGuardarTipo.setBackground(new java.awt.Color(255, 255, 255));
        btnGuardarTipo.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnGuardarTipo.setText("Continuar");
        btnGuardarTipo.setBorder(null);
        btnGuardarTipo.setOpaque(false);
        btnGuardarTipo.setPreferredSize(new java.awt.Dimension(45, 17));
        btnGuardarTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarTipoActionPerformed(evt);
            }
        });

        btnRegresar.setBackground(new java.awt.Color(255, 255, 255));
        btnRegresar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.setBorder(null);
        btnRegresar.setOpaque(false);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBackgroundLayout = new javax.swing.GroupLayout(pnlBackground);
        pnlBackground.setLayout(pnlBackgroundLayout);
        pnlBackgroundLayout.setHorizontalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackgroundLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTituloTipoMaterial1, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                    .addComponent(cboSubtipoMaterial, 0, 0, Short.MAX_VALUE)
                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblTituloTipoMaterial)
                        .addGap(15, 15, 15)))
                .addGap(87, 87, 87))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackgroundLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardarTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackgroundLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(iconMaterial)
                .addGap(124, 124, 124))
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(cboTipoMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBackgroundLayout.setVerticalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(iconMaterial)
                .addGap(33, 33, 33)
                .addComponent(lblTituloTipoMaterial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboTipoMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(lblTituloTipoMaterial1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboSubtipoMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnGuardarTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboTipoMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTipoMaterialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboTipoMaterialActionPerformed

    private void cboSubtipoMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboSubtipoMaterialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboSubtipoMaterialActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        dispose();
        Inicio ini = new Inicio();
        ini.setVisible(true);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnGuardarTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarTipoActionPerformed
        // TODO add your handling code here:
      /**Abrir el formulario correspondiente según la opción seleccionada en el combobox de Subtipo material **/
       String item = cboSubtipoMaterial.getSelectedItem().toString();
       if(item.equals("Libro"))
       {
           dispose();
                Libro lib = new Libro();
                lib.setVisible(true);
       }
       if(item.equals("Revista"))
       {
           dispose();
                Revista rev = new Revista();
                rev.setVisible(true);
       }
       if(item.equals("CD"))
       {
           dispose();
                CD cd = new CD();
                cd.setVisible(true);
       }
       if(item.equals("DVD"))
       {
           dispose();
                DVD dvd = new DVD();
                dvd.setVisible(true);
       }
      
       
       
    }//GEN-LAST:event_btnGuardarTipoActionPerformed

    private void cboTipoMaterialItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboTipoMaterialItemStateChanged
        // TODO add your handling code here:
        //**Llenamos el combobox de Subtipo de Material, dependiendo de la opción seleccionada en el primer combobox
        String opcion =(String)cboTipoMaterial.getSelectedItem();
        if(opcion.equals("Material Escrito"))
        {cboSubtipoMaterial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Libro", "Revista"}));       
        
        }if(opcion.equals("Material Audiovisual"))
        {cboSubtipoMaterial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"CD","DVD"}));}
    }//GEN-LAST:event_cboTipoMaterialItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TipoMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TipoMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TipoMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TipoMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TipoMaterial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarTipo;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cboSubtipoMaterial;
    private javax.swing.JComboBox<String> cboTipoMaterial;
    private javax.swing.JLabel iconMaterial;
    private javax.swing.JLabel lblTituloTipoMaterial;
    private javax.swing.JLabel lblTituloTipoMaterial1;
    private javax.swing.JPanel pnlBackground;
    // End of variables declaration//GEN-END:variables
}
